name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello World Action
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Do action-a
        uses: ./action-a
        with:
          MY_NAME: "Chevy"
